# Test Relighting Training Config (Single Image Dataset)
wandb_project: null  # Disable wandb for testing
timestep_sampling: custom_timesteps
unet_input_channels: 4
vae_num_channels: 4
selected_timesteps: [250, 500, 750, 1000]
prob: [0.25, 0.25, 0.25, 0.25]
pixel_loss_type: lpips # l1 l2
pixel_loss_weight: 10.0
latent_loss_type: l2 # l1 l2
latent_loss_weight: 1.0
bridge_noise_sigma: 0.005
conditioning_images_keys: []
conditioning_masks_keys: []
source_key: source_image
target_key: target_image

# DATASET PATHS - Single image test dataset
train_shards:
  - "/home/sougata/LBM/test_dataset/train_single.tar"

validation_shards:
  - "/home/sougata/LBM/test_dataset/val_single.tar"

# Training parameters (reduced for testing)
batch_size: 1
learning_rate: 4e-5
optimizer: AdamW
num_steps: [1, 2]
log_interval: 10
resume_from_checkpoint: false
max_epochs: 2
save_interval: 50
save_ckpt_path: ./test_checkpoints
